server {
    listen 80;
    server_name lp2medoune.com www.lp2medoune.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name lp2medoune.com www.lp2medoune.com;

    # Certificats Let's Encrypt (adaptez le chemin si nécessaire)
    ssl_certificate     /etc/letsencrypt/live/lp2medoune.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lp2medoune.com/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;

    client_max_body_size 10M;

    location / {
        proxy_pass         http://127.0.0.1:5050;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        keep-alive;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
    }
}
